# Form implementation generated from reading ui file 'app/vm_admin_console/view/ui_main_window.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(634, 293)
        font = QtGui.QFont()
        font.setFamily("Space Mono")
        font.setPointSize(13)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(170, 85, 255, 255), stop:1 rgba(85, 0, 127, 255))")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ConnectionLayoutHoriz = QtWidgets.QHBoxLayout()
        self.ConnectionLayoutHoriz.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.ConnectionLayoutHoriz.setContentsMargins(0, -1, -1, -1)
        self.ConnectionLayoutHoriz.setSpacing(6)
        self.ConnectionLayoutHoriz.setObjectName("ConnectionLayoutHoriz")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.ConnectionLayoutHoriz.addItem(spacerItem)
        self.ConnectButton = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConnectButton.sizePolicy().hasHeightForWidth())
        self.ConnectButton.setSizePolicy(sizePolicy)
        self.ConnectButton.setMinimumSize(QtCore.QSize(150, 0))
        self.ConnectButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.ConnectButton.setBaseSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Space Mono")
        font.setPointSize(14)
        self.ConnectButton.setFont(font)
        self.ConnectButton.setStyleSheet("QPushButton {\n"
"background-color: rgba(255, 255, 255, 30);\n"
"color: white;\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 255, 255, 40);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgba(255, 255, 255, 70);\n"
"}\n"
"")
        self.ConnectButton.setObjectName("ConnectButton")
        self.ConnectionLayoutHoriz.addWidget(self.ConnectButton)
        self.verticalLayout.addLayout(self.ConnectionLayoutHoriz)
        self.ConnectionFrame = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConnectionFrame.sizePolicy().hasHeightForWidth())
        self.ConnectionFrame.setSizePolicy(sizePolicy)
        self.ConnectionFrame.setStyleSheet("color: white;\n"
"background-color: none;\n"
"font-family: Space Mono;\n"
"font-size: 20px;\n"
"\n"
"border: 2px solid rgba(255, 255, 255, 100);\n"
"border-radius: 5px;\n"
"")
        self.ConnectionFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.ConnectionFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.ConnectionFrame.setLineWidth(1)
        self.ConnectionFrame.setMidLineWidth(0)
        self.ConnectionFrame.setObjectName("ConnectionFrame")
        self.ConnectionGroup = QtWidgets.QVBoxLayout(self.ConnectionFrame)
        self.ConnectionGroup.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinAndMaxSize)
        self.ConnectionGroup.setContentsMargins(1, 5, -1, 7)
        self.ConnectionGroup.setObjectName("ConnectionGroup")
        self.ConnectionLabelFrame = QtWidgets.QFrame(parent=self.ConnectionFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConnectionLabelFrame.sizePolicy().hasHeightForWidth())
        self.ConnectionLabelFrame.setSizePolicy(sizePolicy)
        self.ConnectionLabelFrame.setStyleSheet("border: None;")
        self.ConnectionLabelFrame.setObjectName("ConnectionLabelFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.ConnectionLabelFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ConnectionLabel = QtWidgets.QLabel(parent=self.ConnectionLabelFrame)
        font = QtGui.QFont()
        font.setFamily("Space Mono")
        font.setPointSize(-1)
        self.ConnectionLabel.setFont(font)
        self.ConnectionLabel.setStyleSheet("color: white;\n"
"background-color: none;\n"
"font-family: Space Mono;\n"
"font-size: 20px;")
        self.ConnectionLabel.setLineWidth(0)
        self.ConnectionLabel.setMidLineWidth(0)
        self.ConnectionLabel.setObjectName("ConnectionLabel")
        self.horizontalLayout.addWidget(self.ConnectionLabel)
        self.ConnectionStatusLabel = QtWidgets.QLabel(parent=self.ConnectionLabelFrame)
        self.ConnectionStatusLabel.setStyleSheet("color: white;\n"
"background-color: none;\n"
"font-family: Space Mono;\n"
"font-size: 20px;")
        self.ConnectionStatusLabel.setObjectName("ConnectionStatusLabel")
        self.horizontalLayout.addWidget(self.ConnectionStatusLabel)
        self.ConnectionGroup.addWidget(self.ConnectionLabelFrame)
        self.ConnectionHostFrame = QtWidgets.QFrame(parent=self.ConnectionFrame)
        self.ConnectionHostFrame.setStyleSheet("border: None")
        self.ConnectionHostFrame.setObjectName("ConnectionHostFrame")
        self.ConnectionHostGroup = QtWidgets.QHBoxLayout(self.ConnectionHostFrame)
        self.ConnectionHostGroup.setSpacing(6)
        self.ConnectionHostGroup.setObjectName("ConnectionHostGroup")
        self.ComnnectionHostLabel = QtWidgets.QLabel(parent=self.ConnectionHostFrame)
        font = QtGui.QFont()
        font.setFamily("Space Mono")
        font.setPointSize(-1)
        self.ComnnectionHostLabel.setFont(font)
        self.ComnnectionHostLabel.setStyleSheet("font-size: 18px;")
        self.ComnnectionHostLabel.setObjectName("ComnnectionHostLabel")
        self.ConnectionHostGroup.addWidget(self.ComnnectionHostLabel)
        self.ConnectionHostLineEdit = QtWidgets.QLineEdit(parent=self.ConnectionHostFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConnectionHostLineEdit.sizePolicy().hasHeightForWidth())
        self.ConnectionHostLineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Space Mono")
        font.setPointSize(-1)
        self.ConnectionHostLineEdit.setFont(font)
        self.ConnectionHostLineEdit.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"font-size: 18px;")
        self.ConnectionHostLineEdit.setObjectName("ConnectionHostLineEdit")
        self.ConnectionHostGroup.addWidget(self.ConnectionHostLineEdit)
        self.ConnectionGroup.addWidget(self.ConnectionHostFrame)
        self.ConnectionPortFrame = QtWidgets.QFrame(parent=self.ConnectionFrame)
        self.ConnectionPortFrame.setStyleSheet("border: None;")
        self.ConnectionPortFrame.setObjectName("ConnectionPortFrame")
        self.ConnectionPortGroup = QtWidgets.QHBoxLayout(self.ConnectionPortFrame)
        self.ConnectionPortGroup.setObjectName("ConnectionPortGroup")
        self.ComnnectionPortLabel = QtWidgets.QLabel(parent=self.ConnectionPortFrame)
        font = QtGui.QFont()
        font.setFamily("Space Mono")
        font.setPointSize(-1)
        self.ComnnectionPortLabel.setFont(font)
        self.ComnnectionPortLabel.setStyleSheet("font-size: 18px;")
        self.ComnnectionPortLabel.setObjectName("ComnnectionPortLabel")
        self.ConnectionPortGroup.addWidget(self.ComnnectionPortLabel)
        self.ConnectionPortLineEdit = QtWidgets.QLineEdit(parent=self.ConnectionPortFrame)
        font = QtGui.QFont()
        font.setFamily("Space Mono")
        font.setPointSize(-1)
        self.ConnectionPortLineEdit.setFont(font)
        self.ConnectionPortLineEdit.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"font-size: 18px;")
        self.ConnectionPortLineEdit.setObjectName("ConnectionPortLineEdit")
        self.ConnectionPortGroup.addWidget(self.ConnectionPortLineEdit)
        self.ConnectionGroup.addWidget(self.ConnectionPortFrame)
        self.StatusLabel = QtWidgets.QLabel(parent=self.ConnectionFrame)
        self.StatusLabel.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Space Mono")
        font.setPointSize(-1)
        self.StatusLabel.setFont(font)
        self.StatusLabel.setStyleSheet("border: none;\n"
"font-size: 15px;\n"
"color: #FFFFFF")
        self.StatusLabel.setWordWrap(True)
        self.StatusLabel.setObjectName("StatusLabel")
        self.ConnectionGroup.addWidget(self.StatusLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.ConnectionGroup.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.ConnectionFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 634, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VM administration console"))
        self.ConnectButton.setText(_translate("MainWindow", "Connect"))
        self.ConnectionLabel.setText(_translate("MainWindow", "Connection:"))
        self.ConnectionStatusLabel.setText(_translate("MainWindow", "Disconnected"))
        self.ComnnectionHostLabel.setText(_translate("MainWindow", "host:"))
        self.ComnnectionPortLabel.setText(_translate("MainWindow", "port:"))
        self.StatusLabel.setText(_translate("MainWindow", "Current status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
